/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h2' | 'h3' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    linkType?: 'href' | 'page'
    href?: string
    page?: PageReference
    openInNewTab?: boolean
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page'
        href?: string
        page?: PageReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type CbWysiwyg = {
  _type: 'cbWysiwyg'
  content?: BlockContentTextOnly
}

export type CbParagraph = {
  _type: 'cbParagraph'
  content?: string
}

export type CbNavigation = {
  _type: 'cbNavigation'
  links?: Array<
    {
      _key: string
    } & CbNavigationLink
  >
}

export type CbNavigationLink = {
  _type: 'cbNavigationLink'
  label?: string
  link?: CbLink
}

export type MenuSubLink = {
  _type: 'menuSubLink'
  itemId: string
  label: string
  link: CbLink
}

export type MenuLink = {
  _type: 'menuLink'
  itemId: string
  label: string
  link?: CbLink
  dropdown?: MenuDropdown
  subLinks?: Array<
    {
      _key: string
    } & MenuSubLink
  >
}

export type MenuDropdownSection = {
  _type: 'menuDropdownSection'
  title: string
  links: Array<
    {
      _key: string
    } & MenuSubLink
  >
}

export type MenuDropdown = {
  _type: 'menuDropdown'
  sections: Array<
    {
      _key: string
    } & MenuDropdownSection
  >
}

export type MenuGroup = {
  _type: 'menuGroup'
  menuId: string
  title?: string
  links: Array<
    {
      _key: string
    } & MenuLink
  >
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type CbMedia = {
  _type: 'cbMedia'
  mediaType: 'image' | 'video'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  videoFile?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type CbList = {
  _type: 'cbList'
  ordered?: boolean
  items?: Array<
    {
      _key: string
    } & CbListItem
  >
}

export type CbListItem = {
  _type: 'cbListItem'
  content?: string
}

export type CbLink = {
  _type: 'cbLink'
  linkType?: 'external' | 'internal'
  externalUrl?: string
  internalTargetType?: 'page' | 'path'
  internalPage?: PageReference
  internalPath?: string
  openInNewTab?: boolean
}

export type CbImage = {
  _type: 'cbImage'
  media?: CbMedia
}

export type CbHtml = {
  _type: 'cbHtml'
  content?: string
}

export type CbHeading = {
  _type: 'cbHeading'
  content?: string
  level?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
}

export type CbGroup = {
  _type: 'cbGroup'
  children?: Array<
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
  >
}

export type CbCover = {
  _type: 'cbCover'
  backgroundMedia?: CbMedia
  content?: Array<
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
  >
}

export type CbColumns = {
  _type: 'cbColumns'
  columns?: Array<
    {
      _key: string
    } & CbColumn
  >
}

export type CbColumn = {
  _type: 'cbColumn'
  children?: Array<
    | ({
        _key: string
      } & CbButton)
    | ({
        _key: string
      } & CbHeading)
    | ({
        _key: string
      } & CbParagraph)
    | ({
        _key: string
      } & CbWysiwyg)
    | ({
        _key: string
      } & CbHtml)
    | ({
        _key: string
      } & CbImage)
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
  >
}

export type CbButtons = {
  _type: 'cbButtons'
  items?: Array<
    {
      _key: string
    } & CbButton
  >
}

export type CbButton = {
  _type: 'cbButton'
  label?: string
  actionType: 'button' | 'link'
  link?: CbLink
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heading?: string
  menu: MenuGroup
  legalMenu?: MenuGroup
  showDefaultLegalLinks?: boolean
  copyrightText?: string
}

export type Header = {
  _id: string
  _type: 'header'
  _createdAt: string
  _updatedAt: string
  _rev: string
  positiveLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  negativeLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  primaryMenu: MenuGroup
  secondaryMenu: MenuGroup
  languageToggleLabelEn?: string
  languageToggleLabelAe?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page'
      href?: string
      page?: PageReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  gtmScript?: string
  gaScript?: string
  cookiePolicyScript?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type LegalPageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'legalPage'
}

export type HomePageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'homePage'
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?: PageReference | LegalPageReference | HomePageReference
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  language: string
  headerVariant: 'positive' | 'negative'
  pageBuilder?: Array<
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    canonicalUrl?: string
    noIndex?: boolean
    ogTitle?: string
    ogDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }
  structuredData?: string
}

export type LegalPage = {
  _id: string
  _type: 'legalPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: 'privacy-policy' | 'terms-and-conditions'
  language: string
  headerVariant: 'positive' | 'negative'
  content: BlockContent
  structuredData?: string
  seo?: {
    metaDescription?: string
    canonicalUrl?: string
    noIndex?: boolean
    ogTitle?: string
    ogDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  language: string
  headerVariant: 'positive' | 'negative'
  pageBuilder?: Array<
    | ({
        _key: string
      } & CbButtons)
    | ({
        _key: string
      } & CbColumns)
    | ({
        _key: string
      } & CbGroup)
    | ({
        _key: string
      } & CbList)
    | ({
        _key: string
      } & CbNavigation)
    | ({
        _key: string
      } & CbCover)
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    canonicalUrl?: string
    noIndex?: boolean
    ogTitle?: string
    ogDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }
  structuredData?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | PageReference
  | BlockContentTextOnly
  | SanityImageAssetReference
  | BlockContent
  | CbWysiwyg
  | CbParagraph
  | CbNavigation
  | CbNavigationLink
  | MenuSubLink
  | MenuLink
  | MenuDropdownSection
  | MenuDropdown
  | MenuGroup
  | SanityFileAssetReference
  | CbMedia
  | CbList
  | CbListItem
  | CbLink
  | CbImage
  | CbHtml
  | CbHeading
  | CbGroup
  | CbCover
  | CbColumns
  | CbColumn
  | CbButtons
  | CbButton
  | Footer
  | Header
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | TranslationMetadata
  | InternationalizedArrayReference
  | LegalPageReference
  | HomePageReference
  | InternationalizedArrayReferenceValue
  | HomePage
  | LegalPage
  | Page
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol
